spring:
  application:
    name: rent-a-car

  datasource:
    url: jdbc:mysql://localhost:3306/rentacardb
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8010